name: Wedding Day Texts Front-end Message Display app
on:
  pull_request:
    branches: [ "main", "develop" ]
#  push:
#    branches: [ "develop", "main" ]
#  workflow_dispatch:
#    inputs:
#      AWS_REGION:
#        description: 'Region to deploy functions and later on cloudformation to'
#        required: true
#        default: 'us-east-2'
#      STAGE_NAME:
#        description: 'What stage to deploy to. right now just adds to naming of services'
#        required: false
#        default: 'test'
#      AWS_HOSTING_BUCKET:
#        description: 'Where should we deploy the front-end react application to?'
#        required: true
#        default: 'not configured yet'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]
    steps:
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: '${{ secrets.AWS_ROLE_TO_ASSUME }}'
          role-session-name: GithubTriggeredDeployment
          aws-region: '${{ secrets.AWS_REGION }}'
      - name: Copy files over to bucket
        run: 'aws s3 cp -r client/build s3://${{ secrets.AWS_HOSTING_BUCKET }}'