name: Wedding Day Texts Front-end Message Display app
on:
#  pull_request:
#    branches: [ "main", "develop" ]
#  push:
#    branches: [ "develop", "main" ]
  workflow_dispatch:
    inputs:
      AWS_REGION:
        description: 'Region to deploy functions and later on cloudformation to'
        required: true
        default: 'us-east-2'
      STAGE_NAME:
        description: 'What stage to deploy to. right now just adds to naming of services'
        required: false
        default: 'test'
      AWS_HOSTING_BUCKET:
        description: 'Where should we deploy the front-end react application to?'
        required: true
        default: 'wedding-day-texts-display-bucket'
      AWS_ROLE_TO_ASSUME:
        description: 'Role to assume for credentials (arn value)'
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: '${{ github.events.input.AWS_ROLE_TO_ASSUME }}'
          role-session-name: GithubTriggeredDeployment
          aws-region: '${{ github.events.input.AWS_REGION }}'
      - name: Copy files over to bucket
        run: 'aws s3 cp -r client/build s3://${{ github.events.input.AWS_HOSTING_BUCKET }}/${{ github.events.input.STAGE_NAME }}'