name: Wedding Day Texts Front-end Message Display app
on:
  pull_request:
    branches: [ "main", "develop" ]
#  push:
#    branches: [ "develop", "main" ]
#  workflow_dispatch:
#    inputs:
#      AWS_REGION:
#        description: 'Region to deploy functions and later on cloudformation to'
#        required: true
#        default: 'us-east-2'
#      STAGE_NAME:
#        description: 'What stage to deploy to. right now just adds to naming of services'
#        required: false
#        default: 'test'
#      AWS_HOSTING_BUCKET:
#        description: 'Where should we deploy the front-end react application to?'
#        required: true
#        default: 'not configured yet'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
          cache: "npm"
          cache-dependency-path: client/package-lock.json
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: '${{ secrets.AWS_ROLE_TO_ASSUME }}'
          role-session-name: GithubTriggeredDeployment
          aws-region: '${{ secrets.AWS_REGION }}'
      - uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: WeddingDayTextsDisplaySiteHost
          template: infrastructure/hosted-react-app-template.yaml
          parameter-overrides: "StageName=${{ secrets.STAGE_NAME }},AwsHostingBucket=${{ secrets.AWS_HOSTING_BUCKET }}"
          no-fail-on-empty-changeset: true