name: Wedding Day Texts Test/Build/Deploy Github Action
on:
  push:
    branches: [ "develop", "main" ]
  workflow_dispatch:
    inputs:
      AWS_REGION:
        description: 'Region to deploy functions and later on cloudformation to'
        required: true
        default: 'us-east-2'
      STAGE_NAME:
        description: 'What stage to deploy to. right now just adds to naming of services'
        required: false
        default: 'test'
      AWS_HOSTING_BUCKET:
        description: 'Where should we deploy the front-end react application to?'
        required: true
        default: 'not configured yet'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Navigate to client
        run: cd client
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Front-end Tests
        run: yarn test
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: '${{ github.event.inputs.AWS_REGION }}'
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 3000
          role-session-name: GithubTriggeredDeployment
      - uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: WeddingDayTextsDisplaySiteHost
          template: infrastructure/hosted-react-app-template.yaml
          parameter-overrides: "STAGE_NAME=${{ github.event.inputs.STAGE_NAME }},AWS_HOSTING_BUCKET=${{ github.event.inputs.AWS_FUNCTION_BUCKET }}"
          no-fail-on-empty-changeset: true