AWSTemplateFormatVersion: 2010-09-09

Parameters: # params passed to "--parameter-overrides" in CLI
  AwsHostingBucket:
    Type: String
    Description: 'Where should we deploy the front-end react application to?'
  StageName:
    Type: String
    Description: 'Stage of deployment'

Resources:
  # Create an S3 Bucket that serves a static website (i.e. React app)
  HostingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - ''
        - - !Ref AwsHostingBucket
          - '-'
          - !Ref StageName
      AccessControl: PublicRead # visitors need to be able to access the sie
      WebsiteConfiguration: # this makes the S3 Bucket a static website/app
        IndexDocument: index.html # default object served when visiting S3 domain
        ErrorDocument: index.html # just send to app, let React handle errors and routing

  # Add a Bucket Policy that lets public visitors access the web app
  HostingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref HostingBucket
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement: # lets the public access/view the contents of your Bucket, i.e. web app
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*' # wildcard, allow all requests
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref HostingBucket, /*]]

Outputs:
  WebsiteURL:
    Value: !GetAtt HostingBucket.WebsiteURL
    Description: URL for website hosted on S3